name: "Go Coverage Threshold Action"
description: "Show coverage difference between branches in a pull request"
author: "Jimmy Yan"
inputs:
  path:
    description: "path to git repo"
    default: "."
  coverprofile:
    description: "path to coverage profile"
  module:
    description: "the Go module name"
  threshold:
    description: "coverage threshold (0.00-100.00)"
    default: "0"
  logger-level:
    description: "logger level (debug, info, warn, error)"
    default: "info"
  token:
    description: "GitHub token for API access"
    default: ${{ github.token }}
  conf:
    description: "path to config file"
    default: "gocov-conf.yaml"
  print-uncovered-lines:
    description: "print uncovered lines"
    default: "false"
outputs:
  gocov:
    description: "the coverage difference (0.00-100.00)"
runs:
  using: "docker"
  image: "Dockerfile"
